### ISSUE TITLE
расширение

### ISSUE THREAD

**Issue by paulin-mipt** [BikeevArtur/weather-prognosis#2]
https://github.com/BikeevArtur/weather-prognosis/blob/2408b6231b82119ae1a5800ee87d5b1d12ccd6d8/weather_prognosis.py#L29

А расширение .json?

**Comment by BikeevArtur** [comment]
Я наверное неправильно написал в комментарии: weather-prognosis возвращает в файл словарь с информацией в строковом виде, а weather-analisis парсит ее с помощью json.loads; менять формат файла не нужно

**Comment by paulin-mipt** [comment]
Нужно! Я же не говорю, что это не будет работать, я говорю, что json
правильно хранить в *.json

2018-05-23 21:54 GMT+03:00 BikeevArtur <notifications@github.com>:
